config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :weekly_todo_lists
  resources :todo_lists do
  	resources :todo_items do
  	  member do
  	  	patch :complete
  	  end
  	end
  end
  root 'todo_lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
  	!completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items
end

app/models/weekly_todo_list.rb
class WeeklyTodoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  
  def index
    flash[:notice] = "ようこそ。本日は#{Date.today}です。"
  end

  def create
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to todo_list_path(@todo_list)
  end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def destroy
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.destroy
    redirect_to todo_list_path(@todo_list)
  end

  def complete
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.update_attribute(:completed_at, Time.now) 
    redirect_to @todo_list, notice: "Todo item completed"
  end
 
  private
    def todo_item_params
      params.require(:todo_item).permit(:content, :difficulty, :deadline)
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def sort_column
      @todo_list = TodoList.find(params[:todo_list_id])
      @todo_item = @todo_list.todo_items.find(params[:id])
      @todo_item.column_deadlines.include?(params[:sort]) ? params[:sort] : "deadline"
    end
end

app/controllers/todo_lists_controller.rb
# -*- coding: utf-8 -*-
class TodoListsController < ApplicationController

  def index
  	@todo_lists = TodoList.all
  end

  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
 
    @todo_list.save
    redirect_to @todo_list
  end

  def update
    @todo_list = TodoList.find(params[:id])
 
    if @todo_list.update(todo_list_params)
      redirect_to @todo_list
    else
      render 'edit'
    end
  end

  def destroy
  	@todo_list = TodoList.find(params[:id])
  	@todo_list.destroy

  	redirect_to todo_lists_path
  end

  def edit
  	@todo_list = TodoList.find(params[:id])
  end

  def show
  	@todo_list = TodoList.find(params[:id])
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:title)
  end


end

app/controllers/weekly_todo_lists_controller.rb
class WeeklyTodoListsController < ApplicationController

  def index
    @weekly_todo_lists = WeeklyTodoList.all
  end

  def new
  end

  def create
    @weekly_todo_list = WeeklyTodoList.new(weekly_todo_list_params)
    @weekly_todo_list.save
    redirect_to @weekly_todo_list
  end

  def show
    @weekly_todo_lists = WeeklyTodoList.all
  	@weekly_todo_list = WeeklyTodoList.find(params[:id])
  end

  private

  def weekly_todo_list_params
    params.require(:weekly_todo_list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/weekly_todo_lists_helper.rb
module WeeklyTodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="sampleApp">
<html>
  <head>
    <title>Tododemo2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
  	<% flash.each do |key, value| %>
  		<%= content_tag(:div, value, class: "#{key}") %>
	  <% end %>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for ([@todo_list, @todo_list.todo_items.build]), :html => { :class => "form-horizontal todo_list" } do |f| %>

  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-3' %>
    <div class="col-lg-6">
      <%= f.text_field :content, :class => 'form-control', :placeholder => 'add todo item'%>
    </div>
    <%=f.error_span(:content) %>
  </div>

  <div class="form-group">
    <%= f.label :difficulty, :class => 'control-label col-lg-3' %>
    <div class="col-lg-6">
      <%= f.select :difficulty, {'easy' => 1, 'normal' => 2, 'hard' => 3}, :class => 'form-control' %>
    </div>
    <%=f.error_span(:difficulty) %>
  </div>

  <div class="form-group">
    <%= f.label :deadline, :class => 'control-label col-lg-3' %>
    <div class="col-lg-6">
      <%= f.time_select :deadline, :class => 'form-control' %>
    </div>
    <%=f.error_span(:deadline) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-8 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/todo_items/_header.html.erb
<%- model_class = TodoList -%>
<% @todo_list.todo_items.each do |todo_item| %>

  <% if Tod::TimeOfDay(todo_item.deadline) > Tod::TimeOfDay(Time.now) %>
    <% if !todo_item.completed? %>
	  <h2>It is time to <%= todo_item.content %></h2>
	  <% temp = Tod::TimeOfDay(todo_item.deadline) - Tod::TimeOfDay(Time.now) %>
	  <h2>残り<%= temp %></h2>
	<% end %>
  <% end %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<%- model_class = TodoList -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%=t '.actions', :default => t("helpers.complete") %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:difficulty) %></th>
      <th><%= model_class.human_attribute_name(:deadline) %></th>
      <th><%=t '.actions', :default => t("helpers.delete") %></th>
    </tr>
  </thead> 
  <tbody>
  	<% @todo_list.todo_items.each do |todo_item| %>
      <tr>
        <% if todo_item.completed? %>
          <td class="success">
            <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item), method: :patch do %>
              <i style="opacity: 0.4;" class="fa fa-check"></i>
            <% end %>
          </td>
          <td class="success"><p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p></td>
          <td class="success"><%= todo_item.difficulty %></td>
          <td class="success"><%= Tod::TimeOfDay(todo_item.deadline) %></td>
          <td class="success">
            <%= link_to [todo_item.todo_list, todo_item],
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item), method: :patch do %>
              <i class="fa fa-check"></i>
            <% end %>
          </td>
          <td><%= todo_item.content %></td>
          <td><%= todo_item.difficulty %></td>
          <td><%= Tod::TimeOfDay(todo_item.deadline) %></td>
          <td>
            <%= link_to [todo_item.todo_list, todo_item],
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list, :html => { :class => "form-horizontal todo_list" } do |f| %>

  <% if @todo_list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @todo_list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-lg-offset-3 col-lg-6">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-5 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.Overview', :default => t("helpers.links.list overview")),
                todo_lists_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/todo_lists/index.html.erb
<%- model_class = TodoList -%>
<div class="jumbotron text-center">
  <h1>To do list</h1>
  <p>Never too late to learn</p> 
</div>
<table class="table table-striped">
  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= link_to todo_list.title, todo_list_path(todo_list)%><span class="badge"><%= @todo_lists.size %></span></td>
        <td>
          <%= link_to todo_list_path(todo_list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
              <i class="fa fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_todo_list_path,
            :class => 'btn btn-primary' %>

<%= link_to t('.new1', :default => t("helpers.links.new1")),
            new_weekly_todo_list_path,
            :class => 'btn btn-primary' %>

app/views/todo_lists/new.html.erb
<%- model_class = TodoList -%>

<div class="page-header">
  <div class="col-lg-offset-5 col-lg-6">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
</div>
<%= render :partial => 'form' %>

app/views/todo_lists/show.html.erb
<%- model_class = TodoList -%>
<h1 class="page-header">
  <p class="text-center"><%= @todo_list.title %></p>
</h1>

<%= render 'todo_items/header' %>

<%= render "todo_items/todo_item" %>

<%= render "todo_items/form" %>

<%= link_to t('.back', :default => t("helpers.links.list overview")),
              todo_lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.destroy', :default => t("helpers.links.list delete")),
              todo_list_path(@todo_list),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/weekly_todo_lists/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
  </tr>
 
  <% @weekly_todo_list.each do |weekly_todo_list| %>
    <tr>
      <td><%= weekly_todo_list.title %></td>
    </tr>
  <% end %>
</table>

app/views/weekly_todo_lists/new.html.erb
<h1>New Article</h1>

<%= form_for :weekly_todo_list, url: weekly_todo_lists_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/weekly_todo_lists/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @weekly_todo_list.title %>
</p>

<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
  </tr>
 
  <% @weekly_todo_lists.each do |weekly_todo_list| %>
    <tr>
      <td><%= weekly_todo_list.title %></td>
    </tr>
  <% end %>
</table>